name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v12
      with:
        name: pkgscrossllvm
        # If you chose API tokens for write access OR if you have a private cache
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build nixpkgs#pkgsCross.mingw32.llvmPackages.clang --impure
      env:
        NIXPKGS_ALLOW_UNSUPPORTED_SYSTEM: 1
    - run: nix-shell --run "echo OK"
